;以【;】开头代表注释
;以【-】开头+名称表示1级分类
-常用(&App) 
	(&C)entBrowser|chrome.exe
	(&B)lender|blender.exe
	3d(&M)ax|3dsmax.exe
	Photoshop|Photoshop.exe
	(&U)nityHub|Unity Hub.exe
	Unreal Engine|UnrealEditor.exe
	AffinityPhoto|Photo.exe
	
	
	--
	Tim(&T)|Tim.exe
	钉钉(&D)|DingtalkLauncher.exe
	微信(&W)|Wechat.exe
	Pure(&R)ef[参考图]|PureRef.exe
	(&S)nipaste|Snipaste.exe
	Xmind|Xmind.exe
	
	--
	Todesk|ToDesk.exe
	Edge|msedge.exe
	(&L)ogseq|Logseq.exe
	(&G)eek|Geek.exe
	WinSCP|WinSCP.exe
	;AnyDesk|AnyDesk.exe
	;IE(&E)|%ProgramFiles%\Internet Explorer\iexplore.exe
	;2级分隔符【--】
	;StrokesPlus鼠标手势|StrokesPlus.exe
	;Ditto剪贴板|Ditto.exe
;-截图(&Snipaste)
	;【官网：https://zh.snipaste.com/】
	; Snip截图		|Snipaste.exe snip
	; Snip贴图		|Snipaste.exe paste
	; 截图并贴图		|Snipaste.exe snip -o pin
	; 显示/隐藏所有贴图	|Snipaste.exe toggle-images
	; 显示贴图组列表		|Snipaste.exe switch-groups
	; Sinp截图		|XiaoYao_plus[RA_plus]("%getZz%",%"Snipaste.exe"%,2001)
	; Sinp选中图片贴图	|XiaoYao_plus[RA_plus]("%getZz%",%"Snipaste.exe"%,2002)
	; 截图后贴图		|XiaoYao_plus[RA_plus]("%getZz%",%"Snipaste.exe"%,2003)
	; 全屏截图放剪切板	|XiaoYao_plus[RA_plus]("%getZz%",%"Snipaste.exe"%,2004)·
	; 截图放快速文件夹	|XiaoYao_plus[RA_plus]("%getZz%",%"Snipaste.exe"%,2005)
	; 纯文本贴图		|XiaoYao_plus[RA_plus]("%getZz%",%"Snipaste.exe"%,2006)
	;白板			|XiaoYao_plus[RA_plus]("%getZz%",%"Snipaste.exe"%,2007)
-窗口(&Windows)
	;外接ahk脚本名[函数名](函数传参数，可以无参)
	窗口置顶	|huiZz_Window[win_top_zz](1)
	窗口取消置顶	#T|huiZz_Window[win_top_zz](0)
	窗口置顶时透明 	#T|huiZz_Window[win_transparent_top_zz]()
-系统(Sys)
	;在程序名后空格+带参数启动
	控制面板(&S)|Control.exe
	Hosts文件|notepad.exe %A_WinDir%\System32\drivers\etc\hosts
	CMD|%ComSpec%
	Powershell[管理员]|huiZz_System[system_runas_zz](%"powershell.exe"%)
	删除临时文件|EcMenu.exe /TempClean
	重启资源管理器|EcMenu.exe /ReExplorer
	回收站|%WinDir%\explorer.exe ::{645FF040-5081-101B-9F08-00AA002F954E}
	清空回收站|huiZz_System[system_recycle_empty]()
-设计(&Desgin)
	World Machine|World Machine64.exe
	--
	(&A)rtEngine|ArtEngine.exe
	Mixer|Quixel Mixer.exe
	Materialize|Materialize.exe
	--
	Gaea|Gaea.exe
	DragonBonesPro|DragonBonesPro.exe
	CAD迷你看图|DWGView.exe
	--
	溜云库(&L)|liuyunku.exe
	convert|convert.exe
	Billfish|Billfish.exe
	Eagle|Eagle.exe
	EpicGames|EpicGamesLaunchers.exe
	VidJuiceUniTube|VidJuice UniTube.exe
-网盘(&Netdisk)
	葫芦儿.派盘|Huluer.exe
	阿里云盘|aDrive.exe
	百度网盘|BaiduNetdisk.exe
	IDM|IDMan.exe
	比特彗星|BitComet.exe
	(&A)irExplorer|AirExplorer.exe
-工具(&Tool)
	钱迹(&Q)|qianji.exe
	GitHubDesktop|GitHubDesktop.exe
	git-bash|git-bash.exe
	--
	WeGame|WeGame.exe
	Steam|Steam.exe
	--
	Shadowsocks|Shadowsocks.exe
	Clash|Clash.exe
	--
	向日葵|SunloginClient.exe
	--
	按键可视化|keyviz.exe
	周易起名软件|周易起名软件.exe
	系统状态显示|TrafficMonitor.exe
	Google地图|googleearth.exe
	虚拟机(&V)irtualBox|VirtualBox.exe
	OBS Studio|obs64.exe
	JSplacement|JSplacement.exe
	Connecter|Connecter.exe
	PiXYZ|PiXYZStudio.exe
	快捷键查看|OpenArk64.exe
	FreeFileSync|FreeFileSync.exe
	RealTimeSync|RealTimeSync.exe
	抽取图标|tong_CommandLine[ResourcesExtract_ico](%getZz%,%"ResourcesExtract.exe"%)
-办公(&Work)|doc docx xls xlsx ppt pptx wps et dps ods
	word(&W)|winword.exe
	Excel(&E)|excel.exe
	PPT(&T)|powerpnt.exe
	腾讯会议|wemeetapp.exe
	万彩办公大师|officebox.exe
	;以【--】开头名称表示2级分类
	--WPS(&S)
		WPS(&W)|WPS.exe
		ET(&E)|et.exe
		WPP(&P)|wpp.exe
-网址(U&RL)
	;在别名最末尾添加Tab制表符+热键(参考AHK写法:^代表Ctrl !代表Alt #代表Win +代表Shift)，如选中文字按Alt+z百度
	百度(&B)|https://www.baidu.com/s?wd=
	谷歌(&G)|https://www.google.com/search?q=%s&gws_rd=ssl
	翻译(&F)	#z|https://translate.google.com/?sl=auto&tl=zh-CN&text=%S&op=translate
	异次元软件|http://www.iplaysoft.com/search/?s=548512288484505211&q=%s
	淘宝(&T)|https://s.taobao.com/search?q=%s
	京东(&D)|https://search.jd.com/Search?keyword=%s&enc=utf-8
	知乎(&Z)|https://www.zhihu.com/search?type=content&q=
	B站|http://search.bilibili.com/all?keyword=%s
	自动翻译|huiZz_Text[google_translate_auto](%getZz%,auto,en)
	--
	RunAny地址|https://github.com/hui-Zz/RunAny
-图片(im&G)|bmp gif jpeg jpg png tiff webp tga dds
	画图(&T)|mspaint.exe
	Xnview|XnView.exe
	JPEGView|JPEGView.exe
	XnvieMP|xnviewmp.exe
	;ACDSee.exe
	;IrfanView.exe
	图压|图压.exe
	;imageMagick官网：https://imagemagick.org/
	--格式转换
		;功能1示例：图片转格式|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,填转换后的图片格式,1)
		图片生成PDF|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,,15)
		图片生成GIF|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,500,17)
		透明转白色背景JPG|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,jpg,9)
		图片转JPG|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,jpg,1)
		图片转PNG|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,png,1)
		图片转WEBP|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,webp,1)
		PNG转ICO|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,ico,1)
		图像去色|XiaoYao_plus[RA_plus2](%getZz%,%"magick.exe"%,convert $1 -type grayscale $2,$1=#path#|$2=#dir#\#nameNoExt#_black.#ext#)
		;生成固定尺寸图|XiaoYao_plus[RA_plus2](%getZz%,%"magick.exe"%,convert $1 -resize 340x313 -background white -gravity center -extent 340x313 $2,$1=#path#|$2=#dir#\#nameNoExt#_固定尺寸.#ext#)
		裁剪空白部分|XiaoYao_plus[RA_plus2](%getZz%,%"magick.exe"%,convert $1 -trim $2,$1=#path#|$2=#dir#\#nameNoExt#_-trim.#ext#)
		删除exif信息|XiaoYao_plus[RA_plus2](%getZz%,%"magick.exe"%,convert $1 -strip $2,$1=#path#|$2=#dir#\#nameNoExt#_-strip.#ext#)
		50%二值化处理|XiaoYao_plus[RA_plus2](%getZz%,%"magick.exe"%,convert $1 -threshold 50% $2,$1=#path#|$2=#dir#\#nameNoExt#_threshold.#ext#)
	--大小缩放
		;功能示例：无损缩放|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,填缩放比例,3)
		无损放大到200%|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,200%,8)
		无损缩小到50%|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,50%,8)
		尺寸调整[弹框版]|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,,12)
	--图像翻转
		;功能示例：图片旋转|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,填旋转的方向,3)
		水平镜像翻转|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,-flop,13)
		垂直镜像翻转|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,-flip,13)
		;功能3示例：图片旋转|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,填需要旋转的角度,3)
		图片旋转90度|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,90,3)
		图片旋转180度|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,180,3)
		图片旋转270度|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,270,3)
	--图像拼接
		;功能4示例：拼接图片|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,填拼接的方向,4)
		;功能6示例：高级拼接|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,填拼接格式,6)
		棋方格拼接8x8|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,8x8,6)
		棋方格拼接4x4|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,4x4,6)
		棋方格拼接5x5|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,5x5,6)
		高级拼接[弹框版]|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,,18)
		---
		垂直拼接|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,-append,4)
		水平拼接|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,+append,4)
		垂直拼接[弹框版]|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,,10)
		水平拼接[弹框版]|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,,11)
	--图片压缩
		;功能2示例：图片体积压缩|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,填压缩比例数值,2)
		图片体积压缩75%|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,75,2)
		图片体积压缩100%|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,100,2)
	--生成缩略图
		;功能7示例：生成缩略图|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,填缩略图比例,7)
		生成缩略图200x200|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,200x200,7)
		生成缩略图100x100|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,200x200,7)
		;注意：在执行这些命令之前，请确保剪贴板中包含有效的图片，剪贴板中的内容不是一张图片，或者剪贴板为空，上述命令可能会失败。
		;功能5示例：剪贴板图片保存|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,填保存路径,5)
		;剪贴板图片保存[桌面]|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,%A_Desktop%,5)
		;剪贴板图片保存[下载]|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,D:\下载,5)
		;功能8示例：调整图片尺寸|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,填图片尺寸比例,8)
		;尺寸800x600|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,800x600,8)
		;你也可以根据需要只指定一个维度，另一个维度将会按照相应的比例进行调整。例如，如果你只想指定宽度为800像素，而高度则按比例自动调整
		;尺寸800x|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,800x,8)
		;同样地，你也可以只指定高度，而宽度则按比例自动调整。
		;尺寸x600|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,x600,8)
		;如果希望强制将图像拉伸到指定尺寸，可以在尺寸参数后添加感叹号（!）
		;尺寸800x600!|XiaoYao_plus[ImageMagick](%getZz%,%"magick.exe"%,800x600!,8)
		;加边框示例：convert -mattecolor "#000000" -frame 30x30 yourname.jpg rememberyou.png
		;其中，"#000000"是边框的颜色，边框的大小为30x30
		;加边框|XiaoYao_plus[RA_plus2](%getZz%,%"magick.exe"%,convert -mattecolor "#000000" -frame 30x30  $1 $2,$1=#path#|$2=#dir#\#nameNoExt#_边框.#ext#)
-影音(&Video)|avi mkv mp4 rm rmvb flv wmv swf mp3 ts
	;QQPlayer.exe
	;PotPlayer.exe
	;XMP.exe
	云音乐(&C)|cloudmusic.exe
	foobar2000|foobar2000.exe
	;QQ音乐|QQMusic.exe
	Listen1|Listen1.exe
	MPV|mpv.exe
	VLC|vlc.exe
	--
	;功能1示例：视频格式转换|XiaoYao_plus[ffmpeg](%getZz%,%"ffmpeg.exe"%,填转换后的视频格式,1)
	视频音频合并|XiaoYao_plus[ffmpeg](%getZz%,%"ffmpeg.exe"%,,8)
	视频格式转换|XiaoYao_plus[RA_plus2](%getZz%,%"ffmpeg.exe"%,-i $1 $2,$1=#path#|$2=#dir#\#nameNoExt#_转换.填转换后的视频格式)
	转MP4[重编码]|XiaoYao_plus[RA_plus2](%getZz%,%"ffmpeg.exe"%,-i $1 $2,$1=#path#|$2=#dir#\#nameNoExt#_转换.mp4)
	转MP4|XiaoYao_plus[ffmpeg](%getZz%,%"ffmpeg.exe"%,mp4,1)
	转MKV|XiaoYao_plus[ffmpeg](%getZz%,%"ffmpeg.exe"%,mkv,1)
	转AVI|XiaoYao_plus[ffmpeg](%getZz%,%"ffmpeg.exe"%,avi,1)
	转FLV|XiaoYao_plus[ffmpeg](%getZz%,%"ffmpeg.exe"%,flv,1)
	转GIF|XiaoYao_plus[ffmpeg](%getZz%,%"ffmpeg.exe"%,gif,3)
	--
	;功能2示例：音频文件音量调整|XiaoYao_plus[ffmpeg](%getZz%,%"ffmpeg.exe"%,填dB值,·2)	通常可以将音频的增益范围设置在-60dB到60dB之间
	;注意：仅支持音频文件
	增大15db音量|XiaoYao_plus[ffmpeg](%getZz%,%"ffmpeg.exe"%,15dB,2)
	增大30db音量|XiaoYao_plus[ffmpeg](%getZz%,%"ffmpeg.exe"%,30dB,2)
	减少15db音量|XiaoYao_plus[ffmpeg](%getZz%,%"ffmpeg.exe"%,-15dB,2)
	减少30db音量|XiaoYao_plus[ffmpeg](%getZz%,%"ffmpeg.exe"%,-30dB,2)
	--
	;功能3示例：音频格式转换|XiaoYao_plus[ffmpeg](%getZz%,%"ffmpeg.exe"%,填转换后的音频格式,3)
	转MP3|XiaoYao_plus[ffmpeg](%getZz%,%"ffmpeg.exe"%,mp3,3)
	转FLAC|XiaoYao_plus[ffmpeg](%getZz%,%"ffmpeg.exe"%,flac,3)
	转AAC|XiaoYao_plus[ffmpeg](%getZz%,%"ffmpeg.exe"%,aac,3)
	转WAV|XiaoYao_plus[ffmpeg](%getZz%,%"ffmpeg.exe"%,wav,3)
	--
	;功能4示例：提取视频所有音轨音频
	;注意：最多只能提取到4条音轨，再多的话需要修改插件，或者使用专业的视频编辑软件
	提取音轨|XiaoYao_plus[ffmpeg](%getZz%,%"ffmpeg.exe"%,,4)
	提取视频|XiaoYao_plus[ffmpeg](%getZz%,%"ffmpeg.exe"%,,7)
	;功能5示例：提取视频所有字幕
	;注意：最多只能提取到10条字幕，再多的话需要修改插件，或者使用专业的视频编辑软件
	提取字幕|XiaoYao_plus[ffmpeg](%getZz%,%"ffmpeg.exe"%,,5)
	--
	视频压缩|XiaoYao_plus[ffmpeg](%getZz%,%"ffmpeg.exe"%,,6)
-CPDF功能|PDF
	;【官网：https://www.coherentpdf.com/】
	合并所选PDF|XiaoYao_plus[RA_plus2](%getZz%,%"cpdf.exe"%,-merge -remove-duplicate-fonts $1 -o $2,$1=#path#|$2=#dir#\合并_%A_YYYY%%A_MM%%A_DD%_%A_Hour%%A_Min%%A_Sec%.pdf,1)
	以文件名为书签合并所选PDF|XiaoYao_plus[RA_plus2](%getZz%,%"cpdf.exe"%,-merge $1 -remove-duplicate-fonts -merge-add-bookmarks -o $2,$1=#path#|$2=#dir#\文件名标签_%A_YYYY%%A_MM%%A_DD%_%A_Hour%%A_Min%%A_Sec%.pdf,1)
	以元标题为书签合并所选PDF|XiaoYao_plus[RA_plus2](%getZz%,%"cpdf.exe"%,-merge $1 -remove-duplicate-fonts -merge-add-bookmarks -merge-add-bookmarks-use-titles -o $2,$1=#path#|$2=#dir#\元标题标签_%A_YYYY%%A_MM%%A_DD%_%A_Hour%%A_Min%%A_Sec%.pdf,1)
	--
	PDF页面缩放到纵向A4|XiaoYao_plus[RA_plus2](%getZz%,%"cpdf.exe"%,-scale-to-fit a4portrait $1 -scale-to-fit-scale 1 -o $2,$1=#path#|$2=#dir#\#nameNoExt#_纵向A4.pdf)
	PDF页面缩放到横向A4|XiaoYao_plus[RA_plus2](%getZz%,%"cpdf.exe"%,-scale-to-fit a4landscape $1 -scale-to-fit-scale 1 -o $2,$1=#path#|$2=#dir#\#nameNoExt#_横向A4.pdf)
	PDF旋转90度|XiaoYao_plus[RA_plus2](%getZz%,%"cpdf.exe"%,-rotate-contents 90 $1 -o $2,$1=#path#|$2=#dir#\#nameNoExt#_旋转90.pdf)
	--
	按页拆分PDF|XiaoYao_plus[RA_plus2](%getZz%,%"cpdf.exe"%,$1 -split -o $2,$1=#path#|$2=#dir#\#nameNoExt#_页拆分%%%.pdf)
	;按书签拆分PDF，将拆分后的每个文件，文件名为书签标签
	按书签拆分PDF|XiaoYao_plus[RA_plus2](%getZz%,%"cpdf.exe"%,-split-bookmarks 0 $1 -utf8 -o $2,$1=#path#|$2=#dir#\@B.pdf)
	;拆分偶数页，并设置每隔多少页生成一个文件
	只拆分偶数页|XiaoYao_plus[RA_plus2Box](%getZz%,%"cpdf.exe"%,$1 even AND -split -chunk $3 -o $2,$1=#path#|$2=#dir#\#nameNoExt#_偶数页%%%.pdf,请设置每隔多少页生成一个文件,$3)
	只拆分奇数页|XiaoYao_plus[RA_plus2Box](%getZz%,%"cpdf.exe"%,$1 odd AND -split -chunk $3 -o $2,$1=#path#|$2=#dir#\#nameNoExt#_奇数页%%%.pdf,请设置每隔多少页生成一个文件,$3)
	每隔多少页拆分|XiaoYao_plus[RA_plus2Box](%getZz%,%"cpdf.exe"%,-split $1 -o $2 -chunk $3,$1=#path#|$2=#dir#\#nameNoExt#_%%%.pdf,请设置每隔多少页生成一个文件,$3)
	;示例：提取第5页，弹框里填 5
	;提取第2到第5页，弹框里填 2-5；
	;提取第1页、第5页、第7页，就用“,”隔开，弹框里填 1,5,7
	只提取第几页|XiaoYao_plus[RA_plus2Box](%getZz%,%"cpdf.exe"%,$1 $3 -o $2,$1=#path#|$2=#dir#\#nameNoExt#_特定拆分.pdf,请设置要提取第几页内容,$3)
	--
	PDF添加页码|XiaoYao_plus[RA_plus2](%getZz%,%"cpdf.exe"%,-add-text " %Page /%EndPage" -top 100pt -font "Times-Roman" -font-size 20 $1 -o $2,$1=#path#|$2=#dir#\#nameNoExt#_添加页码.pdf)
	压缩PDF|XiaoYao_plus[RA_plus2](%getZz%,%"cpdf.exe"%,-squeeze $1 -o $2,$1=#path#|$2=#dir#\#nameNoExt#_压缩.pdf)
	删除书签|XiaoYao_plus[RA_plus2](%getZz%,%"cpdf.exe"%,-merge -remove-duplicate-fonts $1 -o $2,$1=#path#|$2=#dir#\合并_%A_YYYY%%A_MM%%A_DD%_%A_Hour%%A_Min%%A_Sec%.pdf)
	添加水印|XiaoYao_plus[RA_plus2Box](%getZz%,%"cpdf.exe"%,-stamp-on "$3" $1 -o $2,$1=#path#|$2=#dir#\#nameNoExt#_水印.pdf,请设置需要添加的水印文件路径,$3)
	移除内嵌字体|XiaoYao_plus[RA_plus2](%getZz%,%"cpdf.exe"%,-remove-fonts $1 -o $2,$1=#path#|$2=#dir#\#nameNoExt#_内嵌字体移除.pdf)
	--
	;使用128bit对PDF加密，设置所有者密码和用户密码
	加密PDF|XiaoYao_plus[RA_plus2Box](%getZz%,%"cpdf.exe"%,-encrypt 128bit $3 xiaoyao $1 -o $2,$1=#path#|$2=#dir#\#nameNoExt#_加密.pdf,请设置加密密码,$3)
	解密PDF|XiaoYao_plus[RA_plus2Box](%getZz%,%"cpdf.exe"%,-decrypt $1 owner=$3 -o $2,$1=#path#|$2=#dir#\#nameNoExt#_解密.pdf,请设置加密密码,$3)
-编辑(&Edit)|txt ini cmd bat md ahk html
	;在别名后面添加_:数字形式来透明启动应用(默认不透明,1-100是全透明到不透明)
	记事本(&N)_:88|notepad.exe %getZz%
	Notion|Notion.exe
	Notepad3|Notepad3.exe
	AkelPad|AkelPad.exe
	--
	;将选中文字保存为文本文件[可指定保存路径]，自动抓取选中文字的前面5个字符作为文件名。
	;选中文字保存txt|XiaoYao_plus[Storetext](%getZz%,"填编辑器路径",填保存路径)
	选中文字保存TXT并编辑|XiaoYao_plus[Storetext](%getZz%,%"AkelPad.exe"%,%A_Desktop%)
-文件(&File)|
	WinRAR.exe
	TC文件管理|Totalcmd.exe
	Everything文件秒搜|Everything.exe
	Kindle|Kindle.exe
	SumatraPDF|SumatraPDF.exe
	BCompare|BCompare.exe
	自同步|zisyncd.exe
-输入(inpu&T)
	;当前时间（变量语法参考AHK文档https://wyagd001.github.io/zh-cn/docs/Variables.htm）
	当前时间:*X:@dqsj|%A_YYYY%-%A_MM%-%A_DD% %A_Hour%:%A_Min%:%A_Sec%;
	--
	Gmail邮箱:*X:@yx1|shipeng174@gmail.com;
	QQ邮箱:*X:@yx2|123608960@qq.com;
	163邮箱:*X:@yx3|shipeng174@163.com;
	手机号:*X:@sjh|AjAr07932ZhLd3O2vzY1r4bl8t0xAA==$;
	身份证号:*X:@sfz|410881198902280772$;
	--
	;热键映射,快捷方便,左边Shift+空格=回车键;左手Shift+大小写键=删除键
	;左手回车	<+Space|{Enter}::
	;左手删除	LShift & CapsLock|{Delete}::
-
;1级分隔符【-】并且使下面项目都回归1级分类
;QQ.exe
;使用【&】指定快捷键为C,忽略下面C盘的快捷键C
计算器(&C)|calc.exe
加密工具|huiZz_Text[runany_encrypt](%getZz%,303)
;我的电脑(&Z)|explorer.exe
;以【\】结尾代表是文件夹路径
;C盘|C:\
-
RunCtrl.ahk|C:\Users\czy58\Desktop\RunAny_v2\Lib\RunCtrl.ahk
RunAny.ini|C:\Users\czy58\Desktop\RunAny_v2\RunAny.ini
新建 文本文档 (2).txt|C:\Users\czy58\Desktop\新建 文本文档 (2).txt
Slay the Spire.url|C:\Users\czy58\Desktop\Slay the Spire.url
easytier-gui|C:\Users\czy58\Desktop\easytier-gui.lnk
easytier-gui|C:\Users\czy58\AppData\Local\easytier-gui\easytier-gui.exe


;-docto格式转换功能
;【官网：https://github.com/tobya/DocTo】
;文档转txt|XiaoYao_plus[RA_plus2](%getZz%,%"docto.exe"%,-f $1 -O $2 -T wdFormatText,$1=#path#|$2=#dir#\#nameNoExt#_text.txt)
;文档转pdf|XiaoYao_plus[RA_plus2](%getZz%,%"docto.exe"%,-f $1 -O $2 -T wdFormatPDF,$1=#path#|$2=#dir#\#nameNoExt#_PDF.pdf)
;文档转doc|XiaoYao_plus[RA_plus2](%getZz%,%"docto.exe"%,-f $1 -O $2 -T wdFormatDocumentDefault,$1=#path#|$2=#dir#\#nameNoExt#_Document.doc)
;备注 使用文档说明：https://hui-zz.gitee.io/runany/#/README
;Alt=!
;ctrl=^
;shif=+
;win=#
;默认浏览器打开：批量打开网址|huiZz_Text[text_run_url](%getZz%)
;其他浏览器打开：浏览器批量打开网址|huiZz_Text[text_run_url](%getZz%,浏览器路径.exe)
;无路径浏览器打开：无路径批量打开网址|huiZz_Text[text_run_url](%getZz%,%"chrome.exe"%)










